// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgcdxbllybxgeqttbaqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nY2R4YmxseWJ4Z2VxdHRiYXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTEwOTMsImV4cCI6MjA3MTk2NzA5M30.jx_Sl8hpJACneKu_emv4sqUVbwRAGtdtfStCC7-omI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});